name: Playwright Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer dépendances
        run: npm install

      - name: Installer Playwright
        run: npx playwright install --with-deps

      - name: Lancer les tests
        run: npx playwright test
